### ISSUE TITLE
Error and notification copy

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/messagefrom2016#26]
Currently:

When a user saves a message: _"Message successfully created."_

When a user confirms their email: _"Your email you@domain.com has been confirmed"_

When email confirmation fails (unlikely): _""Unable to confirm your email address. Please contact support@messagefrom2016.com"_

**Comment by mattbaker** [comment]
@deanarutherford — I imagine the first one at least can be changed, it's very programmery in its current form.

**Comment by deanarutherford** [comment]
@mattbaker Haha, yeah, kinda. How about just "Your message has been sent?" 

Need a PDF for this?

**Comment by deanarutherford** [comment]
[message_from_2016_feedback.pdf](https://github.com/mattbaker/messagefrom2016/files/595427/message_from_2016_feedback.pdf)

Here's how I think message sendage confirmation should go. Also, here's a thing I just thought of--maybe that button, the confirmation text, and the confirmation email should say "save" instead of "send"? Since the sending's happening in 2018?

Lemme know if any of this doesn't make sense. @mattbaker @ashanan
